# Generated by Django 6.0.4 on 2026-04-18 01:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_processo', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Número do processo deve seguir o padrão CNJ (ex: 1764352-89.2025.8.06.1818).', regex='^\\d{7}-\\d{2}\\.\\d{4}\\.\\d\\.\\d{2}\\.\\d{4}$')])),
                ('uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, null=True)),
                ('assunto', models.CharField(choices=[('NAO_RECONHECE_OPERACAO', 'NAO_RECONHECE_OPERACAO')], default='NAO_RECONHECE_OPERACAO', max_length=64, null=True)),
                ('sub_assunto', models.CharField(choices=[('GENERICO', 'GENERICO'), ('GOLPE', 'GOLPE')], max_length=20, null=True)),
                ('valor_causa', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('has_contrato', models.BooleanField(default=False)),
                ('has_extrato', models.BooleanField(default=False)),
                ('has_comprovante_credito', models.BooleanField(default=False)),
                ('has_dossie', models.BooleanField(default=False)),
                ('has_demonstrativo_evolucao_divida', models.BooleanField(default=False)),
                ('has_laudo_referenciado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acao', models.CharField(choices=[('DEFENDER', 'DEFENDER'), ('PROPOR_ACORDO', 'PROPOR_ACORDO')], max_length=13)),
                ('valor_acordo', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('resultado_macro', models.CharField(choices=[('NAO_EXITO', 'NAO_EXITO'), ('EXITO', 'EXITO')], max_length=12, null=True)),
                ('resultado_micro', models.CharField(choices=[('ACORDO', 'ACORDO'), ('EXTINCAO', 'EXTINCAO'), ('IMPROCEDENCIA', 'IMPROCEDENCIA'), ('PARCIAL_PROCEDENCIA', 'PARCIAL_PROCEDENCIA'), ('PROCEDENCIA', 'PROCEDENCIA')], max_length=24, null=True)),
                ('valor_condenacao', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('same_action_taken', models.BooleanField()),
                ('valor_acordo_in_range', models.BooleanField(null=True)),
                ('shift_valor_acordo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='legalapp.legalcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('probabilidade_perder_caso', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('valor_esperado_condenacao', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sugestao_acao', models.CharField(choices=[('DEFENDER', 'DEFENDER'), ('PROPOR_ACORDO', 'PROPOR_ACORDO')], max_length=13)),
                ('valor_para_acordo', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='legalapp.legalcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('AUTOS_PROCESSO', 'AUTOS_PROCESSO'), ('CONTRATO', 'CONTRATO'), ('EXTRATO_BANCARIO', 'EXTRATO_BANCARIO'), ('COMPROVANTE_DE_CREDITO', 'COMPROVANTE_DE_CREDITO'), ('DOSSIE', 'DOSSIE'), ('DEMONSTRATIVO_DE_EVOLUCAO_DA_DIVIDA', 'DEMONSTRATIVO_DE_EVOLUCAO_DA_DIVIDA'), ('LAUDO_REFERENCIA', 'LAUDO_REFERENCIA')], max_length=40)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='legalapp/documents/')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='legalapp.legalcase')),
            ],
            options={
                'ordering': ['case_id', 'document_type', 'file_name'],
                'constraints': [models.UniqueConstraint(fields=('case', 'document_type', 'file_name'), name='unique_case_document_entry')],
            },
        ),
    ]
