# Generated by Django 6.0.4 on 2026-04-17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agente_classificacao_risco', models.CharField(max_length=120)),
                ('probabilidade_perder_caso', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('valor_esperado_condenacao', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('agente_sugestao_acordo', models.CharField(max_length=120)),
                ('sugestao_acao', models.CharField(choices=[('DEFENDER', 'DEFENDER'), ('PROPOR_ACORDO', 'PROPOR_ACORDO')], max_length=13)),
                ('valor_para_acordo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='legalapp.legalcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]