# Generated by Django 6.0.4 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalapp', '0002_caserecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecommendation',
            name='decisao_advogado',
            field=models.CharField(blank=True, choices=[('ACEITA', 'ACEITA'), ('REJEITADA', 'REJEITADA')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='caserecommendation',
            name='decisao_advogado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]